apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: downpatch
  namespace: downpatch
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-http01
spec:
  tls:
    - hosts:
        - downpatch.com
      secretName: downpatch-com-tls
  rules:
    - host: downpatch.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: downpatch-web
                port:
                  number: 80
