apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: downpatch-www-redirect
  namespace: downpatch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://downpatch.com$request_uri
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
spec:
  tls:
    - hosts:
        - www.downpatch.com
      secretName: www-downpatch-com-tls
  rules:
    - host: www.downpatch.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: downpatch-web
                port:
                  number: 80
